language: ruby
cache: bundler

rvm:
  - 2.0.0

before_script: 'bundle install'
script: 'bundle exec rake yard'

branches:
  only:
    - master

notifications:
  email:
    - shashikant.jagtap@aol.co.uk
